import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import ProfilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText';
import { motion } from 'framer-motion';
import { LinkArrow } from '@/components/Icons';
import lightBuld from "../../public/images/svgs/miscellaneous_icons_1.svg"

const MotionLink = motion(Link);

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Kyle</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark dark:text-light w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-ful'>
            <div className='w-5/12'> 
              <Image src={ProfilePic} alt='Kyle Nguyen' className='w-full h-auto'
              priority sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw"/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Welcome to my HOME" className='!text-6xl !text-left 
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium '>
              As a fresher in web development, I&#39;m passionate about creating dynamic and user-friendly websites. From front-end design to back-end functionality. Explore my portfolio to see my latest projects and skills in action.
              </p>
              <div className='flex items-center self-start mt-2'>
                <MotionLink href="/dummy.pdf" target={'_blank'} className='flex items-center bg-[#1E3A8A] text-yellow-200  p-2 px-4 rounded-lg text-lg font-semibold hover:bg-light'
                whileHover={{ backgroundColor:["#1E3A8A", "rgba(131,58,180,1)","rgba(253,29,29,1)","rgba(252,176,69,1)","rgba(131,58,180,1)", "#1E3A8A"], transition:{duration: 1.5, repeat: Infinity}}} download={true}>
                  My CV 
                <LinkArrow className='!w-4 ml-1.5' />
                </MotionLink>
                <MotionLink href="mailto:vankien41hust@gmail.com" target={'_blank'} className='p-1 px-3 ml-4 text-lg  font-medium capitalize text-light dark:text-dark rounded-2xl bg-dark dark:bg-light hover:underline' whileTap={{scale:0.9}} whileHover={{y:-3}}>Contact</MotionLink>
              </div>
          </div>
          </div>
        </Layout>
        <div className='absolute right-60 bottom-8 inline-block w-24'>
          <Image src={lightBuld} alt='Kyle' className='w-full h-auto'/>
        </div>
        
      </main>
    </>
  )
}
